/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alumno
 */
public class inscripcionCurso extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inscripcionCurso.class.getName());

    /**
     * Creates new form inscripcionCurso
     */
    public inscripcionCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        panelPersonales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnSiguiente1 = new javax.swing.JButton();
        panelContacto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAnterior2 = new javax.swing.JButton();
        btnSiguiente2 = new javax.swing.JButton();
        panelConfirmacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAnterior3 = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenedor.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Nombre");
        panelPersonales.add(jLabel1);

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        panelPersonales.add(txtNombre);

        btnSiguiente1.setText("Siguiente");
        btnSiguiente1.addActionListener(this::btnSiguiente1ActionPerformed);
        panelPersonales.add(btnSiguiente1);

        panelContenedor.add(panelPersonales, "card2");

        jLabel2.setText("Email:");
        panelContacto.add(jLabel2);
        panelContacto.add(txtEmail);

        btnAnterior2.setText("Anterior");
        btnAnterior2.addActionListener(this::btnAnterior2ActionPerformed);
        panelContacto.add(btnAnterior2);

        btnSiguiente2.setText("Siguiente");
        panelContacto.add(btnSiguiente2);

        panelContenedor.add(panelContacto, "card3");

        jLabel3.setText("Paso Final: Confirmar Datos");
        panelConfirmacion.add(jLabel3);

        btnAnterior3.setText("Anterior");
        panelConfirmacion.add(btnAnterior3);

        btnConfirmar.setText("Confirmar");
        panelConfirmacion.add(btnConfirmar);

        panelContenedor.add(panelConfirmacion, "card4");

        getContentPane().add(panelContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) panelContenedor.getLayout();
        cl.next(panelContenedor);
        
    }//GEN-LAST:event_btnSiguiente1ActionPerformed

    private void btnAnterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior2ActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) panelContenedor.getLayout();
        cl.previous(panelContenedor); // Retrocede a la carta anterior
    }//GEN-LAST:event_btnAnterior2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inscripcionCurso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior2;
    private javax.swing.JButton btnAnterior3;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnSiguiente1;
    private javax.swing.JButton btnSiguiente2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelConfirmacion;
    private javax.swing.JPanel panelContacto;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelPersonales;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
